version: '2'

services:

  fcrepo:
    build:
      context: ./fcrepo/4.7.4-demo
    image: pass/fcrepo:4.7.4-demo
    env_file: .env
    ports: 
      - "${FCREPO_PORT}:${FCREPO_PORT}"
      - "${FCREPO_JMS_PORT}:${FCREPO_JMS_PORT}"
      - "${FCREPO_STOMP_PORT}:${FCREPO_STOMP_PORT}"

  ember:
    build:
      context: ./ember-fcrepo/0.0.1-demo
      args:
        EMBER_GIT_REPO: "${EMBER_GIT_REPO}"
        EMBER_GIT_BRANCH: "${EMBER_GIT_BRANCH}"
    image: pass/ember-fcrepo:0.0.1-demo
    env_file: .env
    depends_on:
      - submission
    ports:
      - "${EMBER_PORT}:${EMBER_PORT}"
    links:
      - submission

  ftpserver:
    build: ./ftpserver/0.0.1-demo
    image: pass/ftpserver:0.0.1-demo
    env_file: .env
    environment:
      PUBLICHOST: "${DOCKER_HOST_ADDRESS}"
    ports:
      - "${FTP_SERVER_PORT}:${FTP_SERVER_PORT}"

  submission:
    build:
      context: ./nihms-submission/1.0.0-SNAPSHOT-demo
      args:
        SUBMISSION_GIT_REPO: "${SUBMISSION_GIT_REPO}"
        SUBMISSION_GIT_BRANCH: "${SUBMISSION_GIT_BRANCH}"
    image: pass/nihms-submission:1.0.0-SNAPSHOT-demo
    depends_on:
      - ftpserver
    env_file: .env
    environment:
      FTP_CONFIGURATION_KEY:
      DOCKER_HOST_ADDRESS: "${DOCKER_HOST_ADDRESS}"
      PY_CGI_PORT: "${PY_CGI_PORT}"
      FTP_SUBMISSION_DEBUG_PORT: "${FTP_SUBMISSION_DEBUG_PORT}"
      SUBMISSION_GIT_REPO: "${SUBMISSION_GIT_REPO}"
      SUBMISSION_GIT_BRANCH: "${SUBMISSION_GIT_BRANCH}"
    ports:
      - "${PY_CGI_PORT}:${PY_CGI_PORT}"
      - "${FTP_SUBMISSION_DEBUG_PORT}:${FTP_SUBMISSION_DEBUG_PORT}"
    links:
      - "ftpserver"