version: '2'

services:

  fcrepo:
    build:
      context: ./fcrepo/4.7.4
    image: dataconservancy/pass-fcrepo:4.7.4-demo
    env_file: .env
    ports: 
      - "${FCREPO_PORT}:${FCREPO_PORT}"
      - "${FCREPO_JMS_PORT}:${FCREPO_JMS_PORT}"
      - "${FCREPO_STOMP_PORT}:${FCREPO_STOMP_PORT}"

  ember:
    build:
      context: ./ember/2.17.0-fcrepo
      args:
        EMBER_GIT_REPO: "${EMBER_GIT_REPO}"
        EMBER_GIT_BRANCH: "${EMBER_GIT_BRANCH}"
    image: dataconservancy/pass-ember:2.17.0-demo
    env_file: .env
    depends_on:
      - submission
    ports:
      - "4200:4200"
    links:
      - submission

  ftpserver:
    build: ./ftpserver
    image: ftpserver
    env_file: .env
    environment:
      PUBLICHOST: "${DOCKER_HOST_ADDRESS}"
    ports:
      - "${FTP_SERVER_PORT}:${FTP_SERVER_PORT}"

  submission:
    build:
      context: ./nihms-submission
      args:
        SUBMISSION_GIT_REPO: "${SUBMISSION_GIT_REPO}"
        SUBMISSION_GIT_BRANCH: "${SUBMISSION_GIT_BRANCH}"
    image: submission
    depends_on:
      - ftpserver
    env_file: .env
    environment:
      FTP_CONFIGURATION_KEY:
      DOCKER_HOST_ADDRESS: "${DOCKER_HOST_ADDRESS}"
      PY_CGI_PORT: "${PY_CGI_PORT}"
      FTP_SUBMISSION_DEBUG_PORT: "${FTP_SUBMISSION_DEBUG_PORT}"
      SUBMISSION_GIT_REPO: "${SUBMISSION_GIT_REPO}"
      SUBMISSION_GIT_BRANCH: "${SUBMISSION_GIT_BRANCH}"
    ports:
      - "${PY_CGI_PORT}:${PY_CGI_PORT}"
      - "${FTP_SUBMISSION_DEBUG_PORT}:${FTP_SUBMISSION_DEBUG_PORT}"
    links:
      - "ftpserver"