version: '2'

services:

  fcrepo:
    build:
      context: ./fcrepo/4.7.5-demo
    image: pass/fcrepo
    env_file: .env
    ports: 
      - "${FCREPO_PORT}:${FCREPO_PORT}"
      - "${FCREPO_JMS_PORT}:${FCREPO_JMS_PORT}"
      - "${FCREPO_STOMP_PORT}:${FCREPO_STOMP_PORT}"

  ember:
    build:
      context: ./ember-fcrepo/0.0.1-demo
      args:
        EMBER_GIT_REPO: "${EMBER_GIT_REPO}"
        EMBER_GIT_BRANCH: "${EMBER_GIT_BRANCH}"
    image: pass/ember-fcrepo
    env_file: .env
    depends_on:
      - submission
      - fcrepo
    ports:
      - "${EMBER_PORT}:${EMBER_PORT}"

  ftpserver:
    build: ./ftpserver/0.0.1-demo
    image: pass/ftpserver
    env_file: .env
    ports:
      - "${FTP_SERVER_PORT}:${FTP_SERVER_PORT}"

  submission:
    build:
      context: ./nihms-submission/1.0.0-SNAPSHOT-demo
      args:
        SUBMISSION_GIT_REPO: "${SUBMISSION_GIT_REPO}"
        SUBMISSION_GIT_BRANCH: "${SUBMISSION_GIT_BRANCH}"
    image: pass/nihms-submission
    depends_on:
      - ftpserver
    env_file: .env
    environment:
      FTP_CONFIGURATION_KEY:
      LOCAL_FTP_SERVER: "${LOCAL_FTP_SERVER}"
      PY_CGI_PORT: "${PY_CGI_PORT}"
      FTP_SUBMISSION_DEBUG_PORT: "${FTP_SUBMISSION_DEBUG_PORT}"
      SUBMISSION_GIT_REPO: "${SUBMISSION_GIT_REPO}"
      SUBMISSION_GIT_BRANCH: "${SUBMISSION_GIT_BRANCH}"
    ports:
      - "${PY_CGI_PORT}:${PY_CGI_PORT}"
      - "${FTP_SUBMISSION_DEBUG_PORT}:${FTP_SUBMISSION_DEBUG_PORT}"
