version: '2'

services:

  ember:
    # 1 GiB
    mem_limit: 1073741824
    logging:
      driver: awslogs
      options:
        awslogs-group: pass
        awslogs-region: us-east-1
        awslogs-stream-prefix: ember

  ftpserver:
    logging:
      driver: awslogs
      options:
        awslogs-group: pass
        awslogs-region: us-east-1
        awslogs-stream-prefix: ftpserver

  submission:
    logging:
      driver: awslogs
      options:
        awslogs-group: pass
        awslogs-region: us-east-1
        awslogs-stream-prefix: submission

  fcrepo:
      # 1 GiB
      mem_limit: 1073741824
      logging:
        driver: awslogs
        options:
          awslogs-group: pass
          awslogs-region: us-east-1
          awslogs-stream-prefix: fcrepo