version: '2'

services:

  ember:
    build:
      context: ./pass-ember
      args:
        EMBER_GIT_REPO: "${EMBER_GIT_REPO}"
        EMBER_GIT_BRANCH: "${EMBER_GIT_BRANCH}"
    image: pass
    env_file: .env
    depends_on:
      - submission
    environment:
      EMBER_GIT_REPO: "${EMBER_GIT_REPO}"
      EMBER_GIT_BRANCH: "${EMBER_GIT_BRANCH}"
    ports:
      - "4200:4200"
    links:
      - submission

  ftpserver:
    build: ./ftpserver
    image: ftpserver
    env_file: .env
    ports:
      - "${FTP_SERVER_PORT}:${FTP_SERVER_PORT}"

  submission:
    build:
      context: ./nihms-submission
      args:
        SUBMISSION_GIT_REPO: "${SUBMISSION_GIT_REPO}"
        SUBMISSION_GIT_BRANCH: "${SUBMISSION_GIT_BRANCH}"
    image: submission
    depends_on:
      - ftpserver
    env_file: .env
    environment:
      FTP_CONFIGURATION_KEY:
      LOCAL_FTP_SERVER: "${LOCAL_FTP_SERVER}"
      PY_CGI_PORT: "${PY_CGI_PORT}"
      FTP_SUBMISSION_DEBUG_PORT: "${FTP_SUBMISSION_DEBUG_PORT}"
      SUBMISSION_GIT_REPO: "${SUBMISSION_GIT_REPO}"
      SUBMISSION_GIT_BRANCH: "${SUBMISSION_GIT_BRANCH}"
    ports:
      - "${PY_CGI_PORT}:${PY_CGI_PORT}"
      - "${FTP_SUBMISSION_DEBUG_PORT}:${FTP_SUBMISSION_DEBUG_PORT}"
    links:
      - "ftpserver"